all:
  children:
    frontend:
      hosts:
        frontend-server:
          ansible_host: 35.170.34.144
    medical_services:
      hosts:
        medical-services-server:
          ansible_host: 35.171.99.113
    specialties:
      hosts:
        specialties-server:
          ansible_host: 3.209.5.159
