#!/bin/bash
# Reads Terraform outputs and generates the Ansible inventory + exports env vars.
# Usage: source scripts/generate_inventory.sh   (use 'source' to export vars to current shell)
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/../terraform"
INVENTORY_FILE="${SCRIPT_DIR}/../ansible/inventory/hosts.yml"
GROUP_VARS_FILE="${SCRIPT_DIR}/../ansible/inventory/group_vars/all.yml"

echo "Reading Terraform outputs..."
cd "${TF_DIR}"

FRONTEND_IP=$(terraform output -raw frontend_eip)
MEDICAL_IP=$(terraform output -raw medical_services_eip)
SPECIALTIES_IP=$(terraform output -raw specialties_eip)

export ECR_FRONTEND_URL=$(terraform output -raw ecr_frontend_url)
export ECR_MEDICAL_SERVICES_URL=$(terraform output -raw ecr_medical_services_url)
export ECR_SPECIALTIES_URL=$(terraform output -raw ecr_specialties_url)
export MEDICAL_SERVICES_DB_HOST=$(terraform output -raw medical_services_db_host)
export SPECIALTIES_DB_HOST=$(terraform output -raw specialties_db_host)
export MEDICAL_SERVICES_PRIVATE_IP=$(terraform output -raw medical_services_private_ip)
export SPECIALTIES_PRIVATE_IP=$(terraform output -raw specialties_private_ip)
export AWS_REGION=$(terraform output -raw aws_region)

echo "Generating Ansible inventory at ${INVENTORY_FILE}..."
mkdir -p "$(dirname "${GROUP_VARS_FILE}")"
cat > "${INVENTORY_FILE}" <<EOF
# Auto-generated by generate_inventory.sh — do not edit manually
all:
  children:
    frontend:
      hosts:
        frontend-server:
          ansible_host: ${FRONTEND_IP}
    medical_services:
      hosts:
        medical-services-server:
          ansible_host: ${MEDICAL_IP}
    specialties:
      hosts:
        specialties-server:
          ansible_host: ${SPECIALTIES_IP}
EOF

cat > "${GROUP_VARS_FILE}" <<EOF
# Auto-generated by generate_inventory.sh — do not edit manually

aws_region: "${AWS_REGION}"

ecr_frontend_url: "${ECR_FRONTEND_URL}"
ecr_medical_services_url: "${ECR_MEDICAL_SERVICES_URL}"
ecr_specialties_url: "${ECR_SPECIALTIES_URL}"

medical_services_db_host: "${MEDICAL_SERVICES_DB_HOST}"
specialties_db_host: "${SPECIALTIES_DB_HOST}"
medical_services_private_ip: "${MEDICAL_SERVICES_PRIVATE_IP}"
specialties_private_ip: "${SPECIALTIES_PRIVATE_IP}"
EOF

echo ""
echo "   Inventory written. Environment variables exported:"
echo "   ECR_FRONTEND_URL=${ECR_FRONTEND_URL}"
echo "   ECR_MEDICAL_SERVICES_URL=${ECR_MEDICAL_SERVICES_URL}"
echo "   ECR_SPECIALTIES_URL=${ECR_SPECIALTIES_URL}"
echo "   MEDICAL_SERVICES_DB_HOST=${MEDICAL_SERVICES_DB_HOST}"
echo "   SPECIALTIES_DB_HOST=${SPECIALTIES_DB_HOST}"
echo "   MEDICAL_SERVICES_PRIVATE_IP=${MEDICAL_SERVICES_PRIVATE_IP}"
echo "   SPECIALTIES_PRIVATE_IP=${SPECIALTIES_PRIVATE_IP}"
echo "   AWS_REGION=${AWS_REGION}"
echo ""
echo "Next step: cd ansible && ansible-playbook playbooks/site.yml"
